
test_no_set_e_script:
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-builders/gitlab_agent_deploy:v2752318-c3e56c1
  tags: [ "runner:main", "size:large" ]
  dependencies: []
  script:
    - "asdasdasd"
    - "true"

test_no_set_e_subshell:
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-builders/gitlab_agent_deploy:v2752318-c3e56c1
  tags: [ "runner:main", "size:large" ]
  dependencies: []
  script:
    - "a=$(asdasdasd)"
    - "true"

test_set_e_script:
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-builders/gitlab_agent_deploy:v2752318-c3e56c1
  tags: [ "runner:main", "size:large" ]
  dependencies: []
  script:
    - set -e
    - "asdasdasd"
    - "true"

test_set_e_subshell:
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-builders/gitlab_agent_deploy:v2752318-c3e56c1
  tags: [ "runner:main", "size:large" ]
  dependencies: []
  script:
  - set -e
  - "a=$(asdasdasd)"
  - "true"
