version: '{branch}.{build}'
shallow_clone: false
platform: x64
skip_branch_with_pr: true

branches:
  only:
    - master

environment:
  GOPATH: C:\gopath
  # Give hints to CMake to find Pythons
  Python2_ROOT_DIR: C:\Python27-x64
  Python3_ROOT_DIR: C:\Python37-x64
  PIP2: pip -q
  PIP3: pip3 -q
  MSYS_ROOT: C:\msys64

install:
  - set PATH=%APPVEYOR_BUILD_FOLDER%\bin;%GOPATH%\bin;%Python2_ROOT_DIR%;%Python2_ROOT_DIR%\Scripts;%Python3_ROOT_DIR%;%Python3_ROOT_DIR%\Scripts;%MSYS_ROOT%\mingw64\bin;%MSYS_ROOT%\usr\bin\;%PATH%
  - git clone --depth 1 https://github.com/datadog/integrations-core
  - "%PIP2% install pyyaml requests prometheus_client six"
  - "%PIP3% install pyyaml requests prometheus_client six"
  - "%PIP2% install integrations-core/datadog_checks_base"
  - "%PIP3% install integrations-core/datadog_checks_base"
  - "%PIP2% install -r integrations-core/directory/requirements.in"
  - "%PIP3% install -r integrations-core/directory/requirements.in"
  - "%PIP2% install integrations-core/directory"
  - "%PIP3% install integrations-core/directory"

cache:
  - '%LOCALAPPDATA%\pip\Cache'

build: off

test_script:
  - cmake -G "MSYS Makefiles" .
  - bash -c "make clang-format"
  - bash -c "make && make -C test run"
  - bash -c "./bin/demo 2"
  - bash -c "./bin/demo 3"

# uncomment to debug builds
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
