version: 2
jobs:
  build:
    docker:
      - image: datadog/datadog-agent-six-cci:latest
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cmake .
            make
      - run:
          name: Lint
          command: |
            make clang-format
            [[ $(git ls-files -m | wc -l) -eq 0 ]]
